/** @type {import('tailwindcss').Config} */
module.exports = {
    content: ["./src/**/*.astro"],
    darkMode: "class",
    theme: {
        extend: {
            fontFamily: {
                body: ['"Geist"', "ui-sans-serif", "system-ui", "sans-serif"],
                heading: ['"Geist"', "ui-sans-serif", "system-ui", "sans-serif"],
                mono: [
                    '"IBM Plex Mono"',
                    "ui-monospace",
                    "SFMono-Regular",
                    "Menlo",
                    "Monaco",
                    "Consolas",
                    "Liberation Mono",
                    "Courier New",
                    "monospace",
                ],
            },
            colors: {
                transparent: "transparent",
                current: "currentColor",
                primary: {
                    main: "rgb(var(--color-primary-main) / <alpha-value>)",
                },
                text: {
                    body: "rgb(var(--color-text-body) / <alpha-value>)",
                    bold: "rgb(var(--color-text-bold) / <alpha-value>)",
                    heading: "rgb(var(--color-text-heading) / <alpha-value>)",
                    muted: "rgb(var(--color-text-muted) / <alpha-value>)",
                    code: "rgb(var(--color-text-code) / <alpha-value>)",
                    link: "rgb(var(--color-text-link) / <alpha-value>)",
                    selection: "rgb(var(--color-text-selection) / <alpha-value>)",
                },
                bg: {
                    body: "rgb(var(--color-bg-body) / <alpha-value>)",
                    code: "rgb(var(--color-bg-code) / <alpha-value>)",
                    selection: "rgb(var(--color-bg-selection) / <alpha-value>)",
                },
                border: {
                    code: "rgb(var(--color-border-code) / <alpha-value>)",
                },
            },
            typography: () => ({
                DEFAULT: {
                    css: {
                        fontSize: "15px",
                        lineHeight: "20.5px",
                        letterSpacing: "-0.3px",
                        color: "var(--text)",
                        maxWidth: "none",
                        h1: {
                            fontSize: "1em",
                            fontWeight: "500",
                            color: "var(--text)",
                            lineHeight: "var(--page-line-height)",
                            letterSpacing: "inherit",
                            marginTop: "calc(3 * var(--page-paragraph))",
                            marginBottom: "0",
                        },
                        h2: {
                            fontSize: "1em",
                            fontWeight: "500",
                            color: "var(--text)",
                            lineHeight: "var(--page-line-height)",
                            letterSpacing: "inherit",
                            marginTop: "calc(3 * var(--page-paragraph))",
                            marginBottom: "0",
                        },
                        h3: {
                            fontSize: "1em",
                            fontWeight: "500",
                            color: "var(--text)",
                            lineHeight: "var(--page-line-height)",
                            letterSpacing: "inherit",
                            marginTop: "calc(3 * var(--page-paragraph))",
                            marginBottom: "0",
                        },
                        h4: {
                            fontSize: "1em",
                            fontWeight: "500",
                            color: "var(--text)",
                            marginTop: "calc(3 * var(--page-paragraph))",
                            marginBottom: "0",
                        },
                        h5: {
                            fontSize: "1em",
                            fontWeight: "500",
                            color: "var(--muted)",
                            marginTop: "calc(2 * var(--page-paragraph))",
                            marginBottom: "0",
                        },
                        h6: {
                            fontSize: "0.85em",
                            fontWeight: "500",
                            color: "var(--subtle)",
                            marginTop: "calc(2 * var(--page-paragraph))",
                            marginBottom: "0",
                        },
                        p: {
                            marginTop: "var(--page-paragraph)",
                            marginBottom: "0",
                        },
                        "h1 + p, h2 + p, h3 + p, h4 + p, h5 + p, h6 + p": {
                            marginTop: "var(--page-paragraph)",
                        },
                        a: {
                            color: "var(--link)",
                            textDecoration: "none",
                            fontWeight: "400",
                            "&:hover": {
                                textDecoration: "underline",
                            },
                        },
                        "h1 a, h2 a, h3 a, h4 a, h5 a, h6 a": {
                            color: "inherit",
                            textDecoration: "none",
                            fontWeight: "inherit",
                        },
                        strong: {
                            fontWeight: "500",
                            color: "var(--text)",
                        },
                        kbd: {
                            color: "var(--text)",
                            backgroundColor: "var(--code)",
                            borderRadius: "2px",
                            borderWidth: "1px",
                            borderColor: "var(--border)",
                            padding: "0.1em 0.4em",
                            fontFamily: "var(--font-mono)",
                            fontWeight: "400",
                            boxShadow: "none",
                        },
                        code: {
                            background: "var(--code)",
                            color: "var(--text)",
                            borderRadius: "2px",
                            padding: "1px 4px",
                            fontFamily: "var(--font-mono)",
                            fontSize: "13px",
                            fontWeight: "400",
                            letterSpacing: "0",
                        },
                        "code::before": { content: "none" },
                        "code::after": { content: "none" },
                        pre: {
                            background: "var(--code)",
                            borderRadius: "2px",
                            border: "0",
                            padding: "8px 42px 8px 12px",
                            fontSize: "13px",
                            lineHeight: "1.6",
                            fontFamily: "var(--font-mono)",
                            color: "var(--text)",
                            marginTop: "1em",
                            marginBottom: "0",
                        },
                        "pre code": {
                            background: "transparent",
                            padding: "0",
                            fontSize: "inherit",
                            color: "inherit",
                        },
                        ul: {
                            listStyleType: "none",
                            paddingLeft: "1.1em",
                            marginTop: "var(--page-paragraph)",
                            marginBottom: "0",
                        },
                        "ul > li": {
                            position: "relative",
                            paddingLeft: "0",
                            marginTop: "0.18em",
                            marginBottom: "0",
                        },
                        "ul > li::before": {
                            content: '""',
                            position: "absolute",
                            left: "-0.85em",
                            top: "calc((20.5px / 2) - 1.5px)",
                            width: "3px",
                            height: "3px",
                            background: "currentColor",
                            borderRadius: "0",
                        },
                        ol: {
                            paddingLeft: "1.3em",
                            marginTop: "var(--page-paragraph)",
                            marginBottom: "0",
                        },
                        "ol > li::marker": {
                            color: "var(--muted)",
                        },
                        blockquote: {
                            borderLeft: "3px solid var(--border)",
                            paddingLeft: "0.75rem",
                            color: "var(--muted)",
                            fontStyle: "normal",
                            quotes: "none",
                            marginTop: "var(--page-paragraph)",
                            marginBottom: "0",
                            background: "transparent",
                        },
                        "blockquote p:first-of-type::before": { content: "none" },
                        "blockquote p:last-of-type::after": { content: "none" },
                        hr: {
                            border: "0",
                            borderTop: "1px solid var(--border)",
                            marginTop: "calc(2 * var(--page-paragraph))",
                            marginBottom: "calc(2 * var(--page-paragraph))",
                        },
                        table: {
                            width: "100%",
                            borderCollapse: "collapse",
                            marginTop: "var(--page-paragraph)",
                            fontSize: "1em",
                        },
                        "th, td": {
                            padding: "0.45rem 0.25rem",
                            borderBottom: "1px solid var(--border)",
                            textAlign: "left",
                            verticalAlign: "top",
                        },
                        th: {
                            color: "var(--muted)",
                            fontWeight: "600",
                        },
                        img: {
                            borderRadius: "10px",
                            boxShadow: "0 0 0 1px var(--media-edge)",
                        },
                        "--tw-prose-body": "var(--text)",
                        "--tw-prose-headings": "var(--text)",
                        "--tw-prose-lead": "var(--text)",
                        "--tw-prose-links": "var(--link)",
                        "--tw-prose-bold": "var(--text)",
                        "--tw-prose-counters": "var(--muted)",
                        "--tw-prose-bullets": "var(--text)",
                        "--tw-prose-hr": "var(--border)",
                        "--tw-prose-quotes": "var(--muted)",
                        "--tw-prose-quote-borders": "var(--border)",
                        "--tw-prose-captions": "var(--muted)",
                        "--tw-prose-code": "var(--text)",
                        "--tw-prose-pre-code": "var(--text)",
                        "--tw-prose-pre-bg": "var(--code)",
                        "--tw-prose-th-borders": "var(--border)",
                        "--tw-prose-td-borders": "var(--border)",
                    },
                },
                newspaper: {
                    css: {},
                },
            }),
        },
    },
    plugins: [require("@tailwindcss/typography")],
};
